package practice_5;

//What was output by the application when you executed it? 2

//What "error" was generated by the application when you executed it? 
//Exception in thread "main" java.lang.ArithmeticException: / by zero
//        at practice_5.Example1.main(example1.java:15)

//Why was this "error" generated at run-time (rather than at compile-time)?
//because the code itself is correct, but the arithmetic execution is incorrect

//What error is generated and why?
//example1.java:31: error: variable ratio might not have been initialized
//        System.out.println("The answer is: " + ratio);
//                                               ^
//1 error
//error: compilation failed
//because ratio variable was not initialized

//What output was generated?
//Divide by 0.
//Done.

//What output was generated?
//Divide by 0.
// java.lang.ArithmeticException: / by zero
//         at practice_5.Example1.main(example1.java:37)
//         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
//         at java.base/java.lang.reflect.Method.invoke(Method.java:565)
//         at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.execute(SourceLauncher.java:258)
//         at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.run(SourceLauncher.java:138)
//         at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.main(SourceLauncher.java:76)
// Done.

//Did the application execute properly or not?
//yes

public class Example1
{
    public static void main(String[] args)
    {
        int denominator, numerator, ratio;

        numerator = 5;
        denominator = 0;

        try 
        {
            ratio = numerator / denominator;
            System.out.println("The answer is: " + ratio);
        }
        catch (ArithmeticException e)
        {
            System.out.println("Divide by 0.");
            e.printStackTrace();
        }

        System.out.println("Done.");
    }
}